### ISSUE TITLE
Negitive Amount is unprocessable

### ISSUE THREAD

**Issue by zacgoodwin** [Rdiger-36/bambulab-ams-spoolman-filamentstatus#1]
Sometimes when a reel gets low the AMS thinks it is a negative % and that throws an error and no spools get update:

2024-12-17 07:38:20
- [A0] PLA Matte 68724DFF (-3%) [[ A073EFA6A7AC4F1BB1BB869022037599 ]]
2024-12-17 07:38:20
Error in message handler: HTTPError: Response code 422 (Unprocessable Entity)

Spoolman Log

2024-12-17 07:41:35
uvicorn.access INFO 172.16.0.145:50868 - "GET /api/v1/spool HTTP/1.1" 200
2024-12-17 07:41:35
uvicorn.access INFO 172.16.0.145:50870 - "PATCH /api/v1/spool/33 HTTP/1.1" 422

**Comment by Rdiger-36** [comment]
Hi @zacgoodwin thx for your request. I have implemented a method to ignore negaive percentages send by the ams
