### ISSUE TITLE
Frequency of update makes it hard to edit a spool

### ISSUE THREAD

**Issue by zacgoodwin** [Rdiger-36/bambulab-ams-spoolman-filamentstatus#2]
When editing a spool the Spoolman page goes nuts and is kind of annoying: 

![image](https://github.com/user-attachments/assets/a7f65f52-6468-4ce1-929f-931b6787ca81)

Would be great to be able to set a pooling frequency

**Comment by Rdiger-36** [comment]
Hi @zacgoodwin thy for your request. I have implemented a new env to set the pollimg interval.
All you have to do is to add the UPDATE_INTERVAL env to your docker container.
You can put in any amount of time in milliseconds you want but minimum 1 Second (1000 ms).
Hope this help you

**Comment by zacgoodwin** [comment]
Thanks!
