### ISSUE TITLE
Spooltag for new spools missing in logs

### ISSUE THREAD

**Issue by zacgoodwin** [Rdiger-36/bambulab-ams-spoolman-filamentstatus#3]
Just put in a fresh PETG spool and am getting this error: 

![image](https://github.com/user-attachments/assets/e81d88ad-a2d3-4488-993c-3fa39c1d865f)

Previously I was able to open the logs to get the spool tag for the filament. I no longer can :(

**Comment by Rdiger-36** [comment]
The Problem is solved. Now it should work properly

**Comment by zacgoodwin** [comment]
Thank you!
